### ISSUE TITLE
Save strips last character

### ISSUE THREAD

**Issue by arnovb-github** [Stumpii/ScintillaNet.WPF#6]
In DocumentForm.xaml.cs, the Save(string filePath) method trims the trailing NULL in line:

bw.Write(scintilla.Text.ToCharArray(), 0, scintilla.Text.Length - 1); // Omit trailing NULL

My experience is that that just strips off the last character. Omitting the -1 gives the desired result.

**Comment by Stumpii** [comment]
Fixed in latest devlop branch.

Thanks, Steve
